termux-setup-storage
apt update
apt upgrade
pkg update && pkg upgrade
pkg install python
pkg install python2
pkg install bash
pkg install libwebp
pkg install git -y
pkg install nodejs -y 
pkg install ffmpeg -y 
pkg install wget
pkg install imagemagick -y
git clone https://github.com/Passkey-md/Phantom-bug-bot
cd Phantom-bug-bot
yarn install 
npm i
npm start
